### ISSUE TITLE
symbolic list element as expression?

### ISSUE THREAD

**Issue by dyc-emet** [jlapeyre/Symata.jl#160]
Hi,
I noticed that right now the list element cannot be used as an expression, e.g.
`a[i]`
,in which a and i are just two symbols, will trigger an error.

**Comment by dyc-emet** [comment]
The expression is not supported and is supposed to trigger an error.

**Comment by jlapeyre** [comment]
Thanks. Yes, it is not supported.  But I had considered a more user-friendly (Symata-level) error.  For instance
```
symata 12> 3[4]
BoundsError("part specification 4 is longer than the depth of the object.", #undef)
```
Although the Symata-level error is no longer working as I want now. As you can see. It is thrown to Julia.

But, I think I did implement subscripted variables. I'll search for if/how I did it.

**Comment by jlapeyre** [comment]
Mathematica
```mathematica
In[1]:= Table[a[i], {10}]

Out[1]= {a[i], a[i], a[i], a[i], a[i], a[i], a[i], a[i], a[i], a[i]}
```

Symata
```julia
symata 4> Table(a(i) , [10])
Out(4) = [a(i),a(i),a(i),a(i),a(i),a(i),a(i),a(i),a(i),a(i)]
````
