### ISSUE TITLE
@symExpr broken

### ISSUE THREAD

**Issue by jlapeyre** [jlapeyre/Symata.jl#170]
This stopped working at some point. It should be fixed and a test added:
```
julia> f1(z) = @symExpr Together(PolyLog(-1,z),(1-z))
f1 (generic function with 1 method)

julia> f1(3)
3*(-1 + :z)^(-2)
```
`z` is only substituted in one place.

**Comment by steinQF** [comment]
This has caused me some trouble already. My workaround is to use `setsymata` followed by `symeval` for substitution, rather than a `@symExpr` of something involving `Replace`.
