### ISSUE TITLE
Viability of Formatting Equations?

### ISSUE THREAD

**Issue by ChrisRackauckas** [jlapeyre/Symata.jl#18]
Mathematica has well formatted equations that make its CAS easy to use. Could this be considered for SJulia? @TotalVerb has a version of LaTeX.jl which can output LaTeX to an IJulia notebook. I am wondering how possible it would be to put these together.

**Comment by jlapeyre** [comment]
Yes, more output formats would be great. "2d" as well as LaTeX-like. If you are interested in coding, I would be happy to help you. I have not thought about it in detail, maybe you have some ideas.

**Comment by jlapeyre** [comment]
Here are some short notebooks with formatted output.

https://github.com/jlapeyre/Symata.jl/tree/master/examples

The latex rendering by github is not very pretty.

**Comment by jlapeyre** [comment]
There are some perl scripts for "2D" display that other CAS's use. This is a good short term solution that is likely fairly easy.

**Comment by jlapeyre** [comment]
Latex printing was implemented implemented a couple of years ago.
