### ISSUE TITLE
Mxpr <===> SymPy translation

### ISSUE THREAD

**Issue by Upabjojr** [jlapeyre/Symata.jl#2]
It would be nice to have the ability to covert Mxpr expressions to and from SymPy expression trees. It is not very complicated, considering that PyCall allows access to Python libraries from Julia.

**Comment by jlapeyre** [comment]
Hi. That would be great. I already had a quick look at the Julia SymPy module. It seemed that it did not offer a way to get into the expressions. But, I didn't look into using PyCall directly.  I planned on getting to it sooner or later. If you know something about SymPy and can make suggestions, I'm interested...

Also,  a Maxima interface would be very useful, but the effort for supporting a CL interface would be very big.

**Comment by Upabjojr** [comment]
Here a simple view on how to operate on SymPy's expression tree from Julia:

```
julia> using PyCall

julia> @pyimport sympy
Warning: imported binding for transpose overwritten in module __anon__
```
Create symbol objects:
```
julia> x = sympy.Symbol("x")
PyObject x

julia> y, z = sympy.symbols("y z")
(PyObject y,PyObject z)
```
Additions, multiplications and powers:
```
julia> a = sympy.Add(x, sympy.Mul(y, z))
PyObject x + y*z

julia> p = sympy.Pow(x, y)
PyObject x**y
```
How to read the arguments of a tree node:
```
julia> a[:args]
(PyObject x,PyObject y*z)

julia> p[:args]
(PyObject x,PyObject y)
```
How to get the node head:
```
julia> pytypeof(p)
PyObject <class 'sympy.core.power.Pow'>

julia> pytypeof(a)
PyObject <class 'sympy.core.add.Add'>
```
Testing head equalities:
```
julia> a2 = sympy.Add(a, 3)
PyObject x + y*z + 3

julia> pytypeof(a2) == pytypeof(a)
true

julia> pytypeof(p) == pytypeof(a)
false
```
I don't know about calling Common Lisp from Julia, there is an interface to Maxima in Sage, but I think that's quite tricky. On the other hand, Python is already supported.

**Comment by jlapeyre** [comment]
Thanks for the information. That is enough to start.

**Comment by jlapeyre** [comment]
Is there a way to get the symbol corresponding to a PyObject that is a symbol ? I mean something like here

```julia
julia> a
PyObject x + y*z

julia> a[:args][2]
PyObject x

julia> dump(a[:args][2])
PyCall.PyObject 
  o: Ptr{PyCall.PyObject_struct} Ptr{PyCall.PyObject_struct} @0x00007f0d62a85c30
```

I want to extract the symbol name 'x'. This is the problem I ran into before. Or if I sympy does an integral or something, I want to extract the new symbols that it sends.

**Comment by Upabjojr** [comment]
A symbol is a terminal leaf, it has no args. The string x is stored in some other variables. I don't have a computer access right now, so I can't verify. I think it should be a[:args][2][:_some name here]

**Comment by Upabjojr** [comment]
Try a[:args][2][:name]

**Comment by jlapeyre** [comment]
Thanks. that works. I can also do [:args] on a leaf and it returns an empty tuple

**Comment by jlapeyre** [comment]
I'll need to extract non-terminal node names (operators, or heads) as well.

**Comment by Upabjojr** [comment]
There aren't non-terminal node names. SymPy is type based. Use pytypeof( )

Each node is a type. There is no single type such as your Mxpr, every kind of node (Add, Mul, Pow) is its own type.

**Comment by Upabjojr** [comment]
Even functions are types in SymPy, such as sympy.sin(...), sympy.exp(...).

**Comment by jlapeyre** [comment]
Sorry, I wasn't clear at all.  I'm looking for an interface that gives access to the fields or parts of these objects. `PyObject <class 'sympy.core.add.Add'>`  is Julia's printed representation of an object with some structure. It looks like I have to go to sympy to learn what the possible structures are, and what the syntax of the printed representations are, then do `string(pytype(a))` and parse the result with a regular expression, and convert the result to symbols. Maybe the strings don't vary much and this is not too hard. But, all the extra allocation and parsing sounds expensive.

**Comment by Upabjojr** [comment]
Why would you parse a string? Why not a recursive function containing a series of nested ifs?

Example:

Function parse(expr)
  If type of expr is Add
    Mxpr{:Plus}( map(parse, expr[:args]) ... )
    If args in null then return zero
  Else if other types
    ...
  Else is is symbol
    ...


In Python there is no such thing as metaprogramming. You cannot work with held expressions. SymPy had to invent its own way. So you need a parser specific to SymPy.

**Comment by jlapeyre** [comment]
Looks like my last comment didn't get registered ?, so I'll repeat it, if I can remember.

I don't understand what you are getting at with the pseudo-code.

 But, I could construct an object whose type I want to recognize, extract its type and then compare. Anyway, doing the translation somehow is a good idea.

**Comment by Upabjojr** [comment]
Well, I know SymPy's API, here is a sympy to mxpr translator I just wrote:

```
using PyCall

@pyimport sympy
@pyimport sympy.core as sympy_core

SympySymbol = sympy_core.symbol["Symbol"]
SympyAdd = sympy_core.add["Add"]
SympyMul = sympy_core.mul["Mul"]
SympyPow = sympy_core.power["Pow"]

const conv_dict = Dict(
    SympyAdd => :Plus,
    SympyMul => :Times,
    SympyPow => :Power,
)

function sympy2mxpr(exp_tree)
    if (pytypeof(exp_tree) in keys(conv_dict))
        return mxpr(conv_dict[pytypeof(exp_tree)], map(sympy2mxpr, exp_tree[:args])...)
    end
    if pytypeof(exp_tree) == SympySymbol
        return Symbol(exp_tree[:name])
    end
    if pyisinstance(exp_tree, SympyNumber)
        if exp_tree[:is_Integer]
            return convert(BigInt, exp_tree)
        end
        if exp_tree[:is_Rational]
            return convert(Rational{BigInt}, exp_tree)
        end 
        return convert(FloatingPoint, exp_tree)
    end
end


# TESTS

function test_sympy2mxpr()
    x, y, z = sympy.symbols("x y z")
    add1 = sympy.Add(x, y, z, 3)
    @assert sympy2mxpr(add1) == mxpr(:Plus, 3, :x, :y, :z)
    mul1 = sympy.Mul(x, y, z, -2)
    @assert sympy2mxpr(mul1) == mxpr(:Times, -2, :x, :y, :z)
    add2 = sympy.Add(x, mul1)
    @assert sympy2mxpr(add2) == mxpr(:Plus, :x, mxpr(:Times, -2, :x, :y, :z))
end
```

**Comment by Upabjojr** [comment]
Here the reverse:

```
const conv_rev = Dict(
    :Plus => sympy.Add,
    :Times => sympy.Mul,
    :Power => sympy.Pow,
)   

function mxpr2sympy(mex)
    if !isa(mex, Mxpr)
        if isa(mex, Symbol)
            return sympy.Symbol(mex)
        end
        if isa(mex, Number)
            return mex
        end
    end
    if mex.head in keys(conv_rev)
        return conv_rev[mex.head](map(mxpr2sympy, mex.args)...)
    end
end

# TEST

function test_mxpr2sympy()
    me1 = mxpr(:Plus, :a, :b,  mxpr(:Times, -3, :z, mxpr(:Power, :x, 2)))
    me2 = mxpr(:Times, 2, :x, :y)
    @assert sympy2mxpr(mxpr2sympy(me1)) == me1
    @assert sympy2mxpr(mxpr2sympy(me2)) == me2
end
```

**Comment by jlapeyre** [comment]
Thanks, this is great. I will integrate this somehow.  Anything else like this you are interested/willing to contribute is welcome.  I'll try to get this in and get an example working,.... maybe using sympy as the backend for factoring an expression. But, I have a lot of work to prepare for a conference next week, so it may take some time.

**Comment by jlapeyre** [comment]
Is there an equivalent for, say, the sine function, of this ?
```julia
SympyPow = sympy_core.power["Pow"]
```

**Comment by Upabjojr** [comment]
> Is there an equivalent for, say, the sine function, of this ?

Yes, for the object reference:
```
sympy.functions["sin"]
```
for the function instantiating the object:
```
sympy.sin
```
I hope that in future versions of PyCall they will unify these two objects by using the call overloading, which was recently added to Julia 0.4

**Comment by jlapeyre** [comment]
I added your code and `Factor` and pushed to master.  In this commit, I made SJulia a module. I also pushed a new version of my Julia REPL fork to support the module. At the moment, SJulia requires SymPy. I have to figure out how to do optional loading. There is also code written in SJulia that I don't load because it slows loading down.

**Comment by jlapeyre** [comment]
Another question:
I can create a SymPy function from an Mxpr like this
```
pyfunc = sympy.Function(string(mex.head))
```
And I can recognize a SymPy function like this
```
if exp_tree[:is_Function] ...
```
I can find the args with `pyfunc[:args]`.  But, how can I recover the name of the function, ie. the head ?

I use `pywrap` so that I can get repl completion to show me available methods (converted to fields in an anonymous type). I try several of them, but can't find the `f` in `f(x)`.

**Comment by Upabjojr** [comment]
> I can create a SymPy function from an Mxpr like this
> `pyfunc = sympy.Function(string(mex.head))`

Careful here, if you call `Function("sin")` you are not creating the `sin` function. Function is meant to be an undefined function in SymPy, with no info about its properties (derivatives, integrals, etc...).

> I can find the args with pyfunc[:args]. But, how can I recover the name of the function, ie. the head?

Again, the name of the function is its type (very strange SymPy, huh?). So try `pytypeof(pyfunc)`.

As I mentioned earlier, Python does not have concepts such as held expressions, metaprogramming is very limited, so SymPy developers had to define types for everything to create the equivalent of M-expressions.

**Comment by jlapeyre** [comment]
Right, I am not calling it with "sin", but rather things like "f".

>Again, the name of the function is its type (very strange SymPy, huh?). So try pytypeof(pyfunc). As I mentioned earlier, Python does not have concepts such as held expressions, metaprogramming is very limited, so SymPy developers had to define types for everything to >create the equivalent of M-expressions.

Yes, I've understood all of that perfectly since I first looked at SymPy weeks ago. It looks like a difficult and heroic task. But, it does not help me understand an undocumented API.  Anyway, I'll try `pytypeof(pyfunc)`.
```julia
julia> mex = @ex f(x)
f(x)

julia> pyfunc = sympy.Function(string(mex.head))
fn (generic function with 1 method)

julia> pytypeof(pyfunc)
ERROR: MethodError: `pytypeof` has no method matching pytypeof(::Function)
```
So that doesn't work.

```julia
julia> g(x) = x
g (generic function with 1 method)

julia> typeof(g) == typeof(pyfunc)
True
```
`pyfunc` is a Julia function.
```julia
julia> x = Symbol("x");

julia> fofx = pyfunc(x)
PyObject f(x)
```
I know I can get information with `fofx[:sym]`, but the possible keywords are not documented, so I don't know what to do. `PyCall` documentation mentions using `pywrap`. So I do `pywrap(fofx)` which creates an anonymous type. I can then use TAB completion at the repl to see a few hundred choices of python methods. I try several that look like they may give me something useful, but they don't.  Maybe it's possible to get the symbol or string `f` via the PyCall API, maybe not. I have no way of knowing. So I extract the name of the function as a symbol from the type by parsing it's printed string representation supplied by PyCall.

```
julia> pytypeof(fofx)
PyObject f

julia> (fofx |> pytypeof |> string |> split)[end]
"f"
```

**Comment by Upabjojr** [comment]
Try something like this:
```
julia> f = sympy.Function("f")
fn (generic function with 1 method)

julia> fx = f(sympy.Symbol("x"))
PyObject f(x)

julia> pytypeof(fx)[:__name__]
"f"
```

**Comment by jlapeyre** [comment]
Thanks,   `pytypeof(fx)[:__name__]` does it.

**Comment by jlapeyre** [comment]
... Francesco, Just to be clear, before I extend it too much, Are you willing to release the code you contributed under the same MIT license that Julia uses ?

**Comment by Upabjojr** [comment]
Yes, OK for the MIT license.

**Comment by Upabjojr** [comment]
Concerning the Function objects, Python allows one to change the metaclass, that is the type of a type. Julia's types are instances of DataType, in Python the equivalent is _type_ . UndefinedFunction in SymPy and _type_ in Python are metaclasses, i.e. a class whose instances are classes. That's the trick they used in SymPy to represent undefined functions.

**Comment by Upabjojr** [comment]
I think that `mxpr2sympy` could be better written by using multiple dispatch.

**Comment by Upabjojr** [comment]
By the way, concerning matrices, in SymPy `exp` stands for the matrix exponential if the argument is a matrix, while Mathematica has `MatrixExp` while `Exp` is a bitwise exponential. I think the parser may need to handle such special cases.

**Comment by jlapeyre** [comment]
Yes, I was thinking the same thing about `mxpr2sympy`. Needs organizing, too.

Thanks for the tips on `exp` etc. I think there will be a lot of details regarding translation. For instance, integrate already returns things that I can't yet translate.

**Comment by jlapeyre** [comment]
I'm closing this as it has been inactive.  But, the Juia--sympy interface needs an overhaul.
