### ISSUE TITLE
Use case issue (if that is useful for you)

### ISSUE THREAD

**Issue by goedman** [jlapeyre/Symata.jl#33]
Hi John,

You mentioned previously it helped you to get use cases. This is a use case I created a few years ago in Mathematica to explain buckling. I wrote a Mathematica version:

https://github.com/goedman/NMfE.jl/blob/master/test/PinnedPinnedFlagpole.nb

I redid it in Symata:

https://github.com/goedman/NMfE.jl/blob/master/test/ch04_vianello_symata.jl

which produces:

julia> include("/Users/rob/.julia/v0.5/NMfE/test/ch04_vianello_symata.jl")
N[res[1, 1]]: 0.0
N[res[2, 1]]: 22.7027027027027
N[res[3, 1]]: 19.110473457675752
OverflowError()
ERROR: LoadError: OverflowError()
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/rob/.julia/v0.5/NMfE/test/ch04_vianello_symata.jl, in expression starting on line 3

I'm expecting the number of terms (which go up quite quickly) hits a limit. The correct answer should
look something like: {0, 22.703, 19.110, 18.669, 18.589, 18.573, 18.570, 18.569}

I'll leave this issue open for a few days, but it is not urgent for me. Just wanted to report it.

Regards,
Rob

-------------------------------------
julia> Pkg.installed("Symata")
v"0.1.0+"

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by jlapeyre** [comment]
Hi Rob,

I fixed the bug and pushed the change. So the current master branch of Symata runs your code.

Except, the following does not work

```
symata> r = f(9,y0(x));
symata> r[:,1]
```

I'm not sure what you wanted there, but the following do work

```
r[1:9,1]
r[1]
Transpose(r)[1]
```

Thanks,
John

**Comment by jlapeyre** [comment]
btw. This is very useful to me. I am interested in seeing any code you write. There are ways to use Symata and notational tricks that I am unaware of.

In case you didn't know, here are some equivalent ways to write the following.

```julia
ReplaceAll( tmpy5(x), K1 => K11[1][1][2] )

ReplaceAll( tmpy5(x), K1 => K11[1,1,2] )

tmpy5(x)  ./  (K1 => K11[1,1,2] )
```

Note that Mma's `/.` is `./` in Symata. The Julia parser forces me to do this.

**Comment by goedman** [comment]
Thanks very much John, with the fix it works flawlessly now. Very impressive. It feels even faster in Symata!

I intended to get Transpose(r)[1].

For ReplaceAll, initially I started off with the /. version of ReplaceAll, but got tripped up by either the reversal of the /. symbol or the parentheses around a single replacement rule (the need for those is shown clearly in your "Difference from Mathematica" notebook).

Thanks again,
Rob

**Comment by jlapeyre** [comment]
Rob,
I am glad it works well!  I would like use your code in collection of examples, if this is ok with you.
John

**Comment by goedman** [comment]
Absolutely, go ahead. In the NMfE repository (same link as above) I've added a reference to the Den Hartog book and added comment lines where I used pinned constraints to solve the constants (K1 & K2).

In the example output, N(..., ...) does not seem to work.

By the way, one of my favorite features in Symata is that I can jump in and out of Symata mode repeatedly to review parts of my @sym begin ... end Julia script. In Symata mode I submit lines from the begin ... end block for testing (e.g. from the TextMate editor using Cmd-E on Mac OS X).

Rob

**Comment by jlapeyre** [comment]
I am really glad this is working for you.  How are you running Julia, from a text editor ?

If I understand what you are saying, you can submit lines to a Julia process from within a buffer in TextMate. And when the process is in Symata mode, these lines are interpreted as Symata. I don't quite follow what you mean by jumping between the modes.

In which example does `N(...,...)` not work ? It seems to be working in the Symata code you showed me. Are you referring to something else.

I looked at your code. Here are some comments.

* you used nested Table commands. I just implemented more of `ConstantArray` so that you can
do

```julia
ConstantArray(0.0, [maxiters,6])
```

* The following construction store all the expressions in a Symata list

```julia
[
  e1
  e2
  e3
]
```
This is nice, I did not know it. But, you can instead use `begin` `end` in the body of the For loop so that intermediate results are not stored.

* You can use string interpolation

```julia
Println("N[res[$i, 1]]: ", ...
```

**Comment by goedman** [comment]
Yes, REPL and an editor (TextMate). All Julia code is written in the editor and submitted to the REPL either through Cmd-R (entire file) or Cmd-E (selection only).

What I mean by jumping in and out is repeatedly using "=" and "backspace" in the REPL and finding the Symata process intact for testing purposes..

ConstantArray(0.0, maxiters) works fine, but:

```
symata 18> maxiters
Out(18) = 4

symata 19> res=ConstantArray(0.0, maxiters)
Out(19) = [0.0,0.0,0.0,0.0]

symata 20> res=ConstantArray(0.0, [maxiters,6])
MethodError(colon,(1,[4,6]))
ERROR: MethodError: no method matching colon(::Int64, ::Symata.Mxpr{:List})
Closest candidates are:
  colon{T<:Real}(::T<:Real, ::Any, ::T<:Real) at range.jl:114
  colon{A<:Real,C<:Real}(::A<:Real, ::Any, ::C<:Real) at range.jl:112
  colon{T}(::T, ::Any, ::T) at range.jl:118
  ...
```

What I mean with N(..., ...) is:

```
symata 13> N(Pi)
Out(13) = 3.141592653589793

symata 14> N(Pi,3)
Out(14) = 3.141592653589793

I expected:
Out(14) = 3.142
```

Usually I'm also inclined to replace the rule in ReplaceAll as below:
```
res[i,5] = Simplify( tmpy5(x) ./ (K1 => K11[1, 1, 2]) )
```
by
```
res[i,5] = Simplify( tmpy5(x) ./ Flatten(K11) )
```

Or, apply Flatten directly on Solve:
```
          K22 = Solve(-tmpy2(l), K2)[1]
          res[i,3] = Simplify( tmpy3(x) ./ K22 )
          res[i,2] = Simplify( tmpy2(x) ./ K22 )
```

Not sure if that is better, but with DSolve() sometimes I need to pick the e.g. 2nd or 3rd rule.

Rob

**Comment by jlapeyre** [comment]
Thanks for the info.

Regarding `ConstantArray`, did you pull a (very) recent master version ? I just added the feature today. Or maybe I forgot to push it. The most recent tagged version `v0.3.0-dev.001` certainly has the feature.

Regarding `N`. That's what I suspected that you meant. I have not yet implemented controlling how many digits are printed. `N` will only increase the number of digits.

**Comment by goedman** [comment]
Thanks John, just now the Symata in the cache was upgraded and ConstantArray works fine. N() is not a high priority for my work.

Rob

**Comment by jlapeyre** [comment]
Good. I will close this now.
