### ISSUE TITLE
Question on @sym-ed code inside functions

### ISSUE THREAD

**Issue by goedman** [jlapeyre/Symata.jl#43]
Hi John,

This question is about usage patterns for Symata inside Julia functions, both in the REPL and in iJulia. Basically I am trying to encapsulate @sym-ed Symata code inside a function and pass arguments to it.

As a (simple) usage example, in package NMfE.jl (not published, but Pkg.clone-able) the script

  https://github.com/goedman/NMfE.jl/blob/master/examples/ch07/WRM/Ex.7.13.jl

generates a Lagrangian polynomial for a Weighted Residual Method using 1 point collocation. Other, maybe the more interesting examples from the book, are 2 point Galerkin and Least Squares, also in the same subdirectory.

In the test script: 

  https://github.com/goedman/NMfE.jl/blob/master/test/ch07_test_symata_func.jl

I experimented with "dynamic scoping". These are of course quite different for Symata and Julia. I guess in Mathematica there is the Block[] (vs. Module[]) construct for this?

My 2 questions:

1. Do you think it would be possible and useful to be able to access local Julia variables, e.g. passed into a function, not just global Julia variables?

2. Is it conceivable to have @sym-ed code inside a function? I think this fool is almost asking for a ‘delayed @sym’?

These type of questions might be something you are not at all interested in or maybe on your long term list. That’s ok and there are ways around both questions (certainly in the case where Symata is exposed to the enduser).

By the way, it’s impressive NMfE.jl builds fine on Travis, including all WRM examples.

Regards,
Rob

**Comment by jlapeyre** [comment]
Hi Rob,

Thanks for asking. I am very interested in these things, just have not run into them yet myself. Here are a couple of solutions.  The interface could be more convenient (in fact I will change some things now). I wrote `SetJ` etc. at the very beginning, but I rarely use them. It is fairly easy to change this interface. It would be useful if you have any design suggestions regarding the things you are trying to do.


```julia
using Symata

function symtest(n)
    r = Symata.exfunc(parse("x^$n"))
    Symata.symprintln(r)
    r
end

function setsymtest(xi)
    Symata.setsymval(:r1,xi)
    Symata.exfunc(parse("r = Unpack(r1)"))
end

julia> setsymtest([1,2,3])
Out(1) = [1,2,3]

julia> symtest(3)
Out(1) = x^3
:x^3

julia> symtest(:c)
Out(2) = x^c
:x^:c
```

John

**Comment by goedman** [comment]
Hi John,

Thanks for your answer. I'm also trying to think back to when I worked on Ryacas to see if I formulate my questions correctly.

SetJ() in combination with @eval works fine. I guess there is a bit of a hygiene issue as it uses global space ( r1 in symtest2() below ), but that should be manageable. 

The crux of my question is indeed in your symtest() example. I believe symtest() works because it recompiles the function at the spot. 

Based on your answer I attempted (many) approaches like those shown below, but somehow combining these I can't get to work.

```
using Symata

function symtest1(n, f)
    r = Symata.exfunc(parse("$(f)"))
    Symata.setsymval(:rf, r)
    r
end

r = symtest1(3, "x^n")
println("r = $r") 
    
# Not quite sure how to convert r above into a Julia function.
# If r is a String we can just parse:

function symtest2(n)
  @sym F(x_) := J(parse("(2x)^n"))
  @sym SetJ(r1, ToString(F(x)))
end

symtest2(4)
@eval f1(x, n) = $(parse(r1))

f1(5, 3) |> display
println()
```
What does work is the approach taken in the first and third examples in:

  https://github.com/goedman/NMfE.jl/blob/master/test/ch07_test_lp_sym_func.jl

but moving the Symata.setsymvals() etc. inside a function fails because the lagrangepolynomial() call is executed when the function tf1 is compiled. That's what I meant by needing a 'delayed @sym'.

Thanks again for your help,
Rob

**Comment by jlapeyre** [comment]
Hi Rob,

I will look at your examples. 

I cleaned up the interface with Julia a bit. There are doc strings for the functions and examples can be found at the bottom of this file https://github.com/jlapeyre/Symata.jl/blob/master/examples/Interface%20with%20Julia.ipynb 

John

**Comment by jlapeyre** [comment]
Does this help ? (This uses the latest commit of Symata. But `Symata.setsymval`, etc. should work as well)

```julia
@sym begin
  lagrangepolynomial(xin_, yin_) := Module([N, sum, num, den, xi=xin, yi=yin],
    begin
      N = Length(xi)
      sum = 0
      For( i=1, i <= N, Increment(i),
        begin
          num = 1.0
          den = 1.0
          For( j=1, j <= N, Increment(j),
            begin
              num = If(j != i, num = num * (x-xi[j]), num)
              den = If(j != i, den = den * (xi[i]-xi[j]), den)
            end
          )
          sum = sum + yi[i] * num/den
        end
      ),
      Return(Simplify(sum))
    end
  )
end

setsymata(:xin, List(0.0,0.5,1.0))
setsymata(:yin, List(0.0,0.6,1.0))

f = @sym Compile(Evaluate(lagrangepolynomial(xin,yin)));

println("\nf(0.75) = ", f(0.75))

function lagrangefunc(x1,y1)
    setsymata(:xin, List(x1...))
    setsymata(:yin, List(y1...))
    symeval(parse("Compile(Evaluate(lagrangepolynomial(xin,yin)))"))
end

f1 = lagrangefunc([0.0,0.5,1.0], [0.0,0.6,1.0])

println("f1(0.75) = ", f1(0.75))
```

**Comment by goedman** [comment]
Wow, that's exactly what I was looking for! Works great! Also tried it with the lagragepolynomial that I had added last week to the NMfE.jl package. I think this opens up Symata usage somewhat akin to Tom Breloff's PlotRecipes.

Thanks again John!

**Comment by jlapeyre** [comment]
I am happy that it works. If you have any feedback on the new choice of names, etc. for the Julia interface, please let me know.

Another thing on the todo list you already mentioned, translate Symata to Julia as expressions or strings.

John

**Comment by goedman** [comment]
Clearly I need to get more experience building SymataRecipes like lagrangepolynomial() in your example and using the structure you've explained above before I really feel qualified to make suggestions. But one of the aspects that through me off occasionally the last couple of days is figuring out where (in Julia or Symata) a function was executing, e.g. parse(). To remedy this I'd been thinking about simply Symata.eval(), Symata.set(), etc.. 

Whenever in Julia mode, it's always Symata.xxx(). Symata right now does not export that many symbols, but this approach certainly minimizes  export collisions between packages. Only @sym would be handy to export (but not absolutely necessary).

If you want to switch and live in Symata land, use isymata() or @sym. Ideally at some point these would merge to make it easier to turn scripts into notebooks and vice versa, e.g. Symata.begin()?

In Symata land one has J(). And currently Julia() to exit in IJulia.

Maybe Symata.end() would be a good counterpart to Symata.begin() to leave Symata mode. 

The final aspect are the 'native' functions, like integrate and derivative. Could they also follow the Symata.xxx() scheme?

Just my (initial) $0.02. 

Rob

**Comment by jlapeyre** [comment]
Hi Rob,
I'm sure you'll develop a better idea of what would be convenient, but we have to start somewhere.

> To remedy this I'd been thinking about simply Symata.eval(), Symata.set(), etc..

Then `set()` would call the same method in the Symata base code.  And every module has its only `eval` methods by default, so `Symata.eval()` is already taken. There could be a submodule, or a separate module. eg `Symata.User.set`, but this is not very convenient.

In the last one or two commits, more symbols are exported. I had been thinking that using Julia would be mostly for development of Symata. But, its obvious now that there could be many uses similar to yours: 
user Julia code that interacts with Symata.

I think its best to follow a Julia, convention, but I am not sure which one. Sometimes a single function is used for getting and setting, sometimes one is prefixed with `set`, sometimes find both `get` and `set`.

Till now, I kept evaluation and parsing separate, because thats what Julia does for Julia code. But, I agree that a single function is needed to do both for `Symata`. I am looking for a way to do that.

The question of which `parse` might be confusing. You can get information using `which(:parse)`. It turns out that `parse` is always the Julia base method. There is no `parse` in Symata. This is because valid  `Julia` and `Symata` syntax are exactly the same. But, `parse` returns an expression that may be a valid Julia or Symata expression, or neither, or both. In fact `Symata.extomx(parse(x))` is equivalent to `parse` in Julia.... now that I think of it, it might be a good idea to implement a function called `parsesymata` that does just that.

> Maybe Symata.end() would be a good counterpart to Symata.begin() to leave Symata mode.

`end` and `begin` are reserved words in Julia; you can't use them for function names.

Whatever symbols we choose have to be good choices in the Symata code base, with `Symata.` stripped, as well as in `Main`, where there may be symbols imported from any other module. For instance `setsymval` means "set symbol value" (ie make Symata binding), but I don't think it is a good choice to be imported into Main (or another module).  `setsymata` is more clear in `Main`, but is redundant in `Symata`.

**Comment by jlapeyre** [comment]
btw., the current interface is not yet consistent with what I wrote above.

**Comment by goedman** [comment]
Hi John,
> Then set() would call the same method in the Symata base code. And every module has its only eval methods by default, so Symata.eval() is already taken. There could be a submodule, or a separate module. eg Symata.User.set, but this is not very convenient.
> 
Agreed. Somehow I was hoping dispatch (with some help) could somehow resolve this (also related to your point that setsymata is redundant in Symata mode).

> In the last one or two commits, more symbols are exported. I had been thinking that using Julia would be mostly for development of Symata. But, its obvious now that there could be many uses similar to yours: user Julia code that interacts with Symata.
> 

In NMfE.jl I’ve switched to import Symata: @sym, symeval, setsymata, getsymata and all my examples and the ch07 tests work fine (I’ll rework some of them to use the new symeval). So for "user Julia code” we’re talking about a limited subset of all symbols you export. For those that develop recipes and need more advanced features, e.g. mpxr manipulation, a larger set of symbols should not be a major obstacle.

I don’t have strong feelings pro or con the new names. I was looking for as much consistency as possible, e.g. given your thought about maybe introducing parsesymata(), should all functions be xxxsymata(), i.e. evalsymata(), setsymata(), etc.?

The function isymata() really does 2 things, going into Symata mode and enabling Symata inside IJulia (and switching to JupyterForm by default). Maybe we could just have the symata()/Julia() pair where symata() acts differently when isdefined(Main, :IJulia) returns true? 

By the way, I was thrilled this morning to see:

	https://discourse.julialang.org/t/big-grant-in-which-julia-plays-a-part/544 <https://discourse.julialang.org/t/big-grant-in-which-julia-plays-a-part/544>

In my mind it also underlines how much Symata is adding to Julia in the engineering domain.

Regards,
Rob

**Comment by jlapeyre** [comment]
> I don’t have strong feelings pro or con the new names. I was looking for as much consistency as possible, e.g. given your thought about maybe introducing parsesymata(), should all functions be xxxsymata(), i.e. evalsymata(), setsymata(), etc.?

Yes, consistency is very important. I hope it is consistent when the dust settles.

> The function isymata() really does 2 things,

I think this is a good suggestion. e.g. `symata()` could switch modes no matter what the interface. Unfortunately, switching modes programatically in the REPL is a PITA. It is relatively easy to set up a key for switching. But, at some point, this should be done.

> By the way, I was thrilled this morning to see:...

Yes, this is good news. People are taking Julia very seriously. But, the grant has nothing to do with Symata. Calling Nemo from Symata would be nice, but that is for later.

**Comment by goedman** [comment]
Hi John,

> Yes, this is good news. People are taking Julia very seriously. But, the grant has nothing to do with Symata. Calling Nemo from Symata would be nice, but that is for later.
> 
Yes, I realized these are not connected. I meant more the fact that one can create a new (symbolic) layer on top of Julia and then easily continue with the results in Julia.

In order to have the original example you provided with symeval in

 https://github.com/goedman/NMfE.jl/blob/master/test/ch07_jl_sym_fnc_ex.jl <https://github.com/goedman/NMfE.jl/blob/master/test/ch07_jl_sym_fnc_ex.jl>

to work, I have to revert the “rework Julia interface again” commit. It’s not quite clear to me why the commit returns an expression (which is not callable) and before the commit it returns a Julia function. Below the error I get before reverting the commit:


ERROR: LoadError: MethodError: objects of type Expr are not callable
 in ytilde(::Float64, ::Float64) at /Users/rob/.julia/v0.5/NMfE/examples/ch07/WRM/Ex.7.13.function.jl:69
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/rob/.julia/v0.5/NMfE/examples/ch07/WRM/Ex.7.13.function.jl, in expression starting on line 70


Regards,
Rob

**Comment by jlapeyre** [comment]
Hi Rob,

I hope it will be clear in the end.
 
Either of the following work.

```
symtranseval(parse("Compile(Evaluate(LagrangePolynomial(xin,yin)))"))
```
```
symparseeval("Compile(Evaluate(LagrangePolynomial(xin,yin)))")
````

Now `symeval`  Symata-evaluates  a Symata expression. This is in analogy to Julia `eval`.  Parsing a string to an Expr and translating the result to Symata are separate processes.

`symparseeval` actually parses, translates, and evaluates.

John

**Comment by goedman** [comment]
Works like a champ John! I'll close this issue now!

**Comment by jlapeyre** [comment]
Good, ... one last thing (well, maybe there will be  others). The `symevalparse` etc. stuff is now documented a bit on the [interaction with julia](http://nbviewer.jupyter.org/github/jlapeyre/Symata.jl/blob/master/examples/Interface%20with%20Julia.ipynb) page.

On the same page, I also introduced a macro `@symExpr` that may be what you are looking for. It evaluates a Symata expression, translates the result to Julia, and inserts it into your Julia code.

**Comment by goedman** [comment]
Thanks John, I'm working through the notebook right now. Until now I've always been focused on what I wanted to get done, now is the time to dig in. @symExpr is certainly a next step!

**Comment by goedman** [comment]
The initial question posed in this issue was about usage patterns. In

 https://github.com/goedman/NMfE.jl/blob/master/test/ch07_jl_sym_fnc_ex.jl

I've kind of summarized my findings for now.

@symExpr's strength is while you are in Julia Main-land (like @sym), less so when in a function intended to return a symbolic result, e.g. shape functions or Lagrangian polynomials.

The big advantage of @symExpr though is that you can name the function arguments, which is important in my mind, e.g. I want the function to be f(x, c1, c2, c3), not f(c1, c2, c3, x). 

I'm sure my usage patterns will evolve and improve over time, but thanks once again for all your help!

Regards, Rob
