### ISSUE TITLE
Upgrading NMfE.jl (using Symata)

### ISSUE THREAD

**Issue by goedman** [jlapeyre/Symata.jl#85]
Hi John,

I'm looking at upgrading NMfE.jl to Julia 0.7 and was wondering if it is your intention indeed to upgrade Symata as well? Of course I know it is a huge undertaking and I do not expect a specific time frame. But if you intend to do it, I'll just keep the Julia 0.6.3 version around and temporarily disable the tests in the Julia 0.7 version.  And if I can help, please let me know.

Hope all is fine with you!

Best, Rob

**Comment by jlapeyre** [comment]
Hi Rob,
Thanks for contacting me about this. For various reasons I have just begun to work on upgrading `Symata.jl`. I hope it goes well. I'll let you know what's up. Also I'll push the changes here as soon as I can. I want to support `NMfE.jl` on v0.7-beta --> v1.0 !

Best,
John

**Comment by goedman** [comment]
That is a great update! As I mentioned, time frame is not my primary concern as it is easy to keep the Julia 0.6.3 version around. Thanks John.
